#!/usr/bin/env python3
import argparse
import json
import os
import platform
import stat
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.anvil_server import (  # noqa: E402
    ANVIL_JAR,
    ANVIL_TOOL_LOG_DIR,
    CONF_DIR,
    chain_provider_provenance,
    copy_new_logs,
    free_port,
    git_provenance,
    snapshot_logs,
    terminate,
)

CLIENT_BIN = CONF_DIR / "zig-out" / "bin" / "anvil_client"
INVOCATIONS_DIR_NAME = "anvil_client_invocations"

# TLS-Anvil invokes the trigger once per test case; without per-invocation
# capture every client's stderr coalesces into one append-only file and
# KeyUpdate.appDataUnderNewKeysSucceeds8446 failures cannot be attributed to
# an individual case. Each invocation now writes its own stderr file under
# INVOCATIONS_DIR_NAME with a utc/epoch_ns/pid start record, and the aggregate
# log becomes a one-line-per-invocation ledger (start record plus the
# invocation file path) instead of raw concatenated client stderr.
INVOCATION_HEADER = "anvil_client start utc=%s epoch_ns=%s pid=%s"
# Exit status for trigger-internal failures (log creation/append): loud,
# nonzero, and reached only before exec, so it can never mask a client exit.
TRIGGER_FAIL_EXIT = 125


def write_run_metadata(output_folder: Path, command: str, port: int, trigger_script: Path) -> None:
    metadata = {
        "generated_at": datetime.now(UTC).isoformat(),
        "host": platform.node(),
        "git": git_provenance(),
        "port": port,
        "client_bin": str(CLIENT_BIN),
        "trigger_script": str(trigger_script),
        "tls_anvil_jar": str(ANVIL_JAR),
        "chain_provider": chain_provider_provenance(),
        "command": command,
    }
    (output_folder / "run_metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")


def _trigger_script_text(client_bin: Path, log_path: Path, invocations_dir: Path) -> str:
    # Paths are embedded as repr() literals, so names containing spaces or
    # quotes stay safe without any shell quoting; the script is stdlib-only.
    return f"""#!/usr/bin/env python3
# Generated by conformance/scripts/anvil_client.py; do not edit.
import os
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

CLIENT_BIN = {str(client_bin)!r}
LOG_PATH = Path({str(log_path)!r})
INVOCATION_DIR = Path({str(invocations_dir)!r})
FAIL_EXIT = {TRIGGER_FAIL_EXIT}

# One time.time_ns() snapshot supplies both the subsecond UTC stamp and the
# integer epoch_ns filename identity: two separate clock reads can straddle
# a tick and disagree, and second-precision stamps cannot order test cases
# that fail 20-60 ms apart.
epoch_ns = time.time_ns()
seconds, remainder_ns = divmod(epoch_ns, 1_000_000_000)
utc = datetime.fromtimestamp(seconds, tz=UTC).strftime("%Y-%m-%dT%H:%M:%S")
stamp = "%s.%06dZ" % (utc, remainder_ns // 1000)
pid = os.getpid()
invocation = INVOCATION_DIR / ("invocation-%d-%d.stderr" % (epoch_ns, pid))
header = {INVOCATION_HEADER!r} % (stamp, epoch_ns, pid)


def fail(action, error):
    sys.stderr.write("anvil_client: cannot %s %s: %s\\n" % (action, invocation, error))
    raise SystemExit(FAIL_EXIT)


try:
    stderr_fd = os.open(invocation, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
except OSError as error:
    fail("create", error)
try:
    ledger_fd = os.open(LOG_PATH, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
except OSError as error:
    fail("open ledger", error)
try:
    os.write(ledger_fd, (header + " stderr=" + repr(str(invocation)) + "\\n").encode())
    os.close(ledger_fd)
except OSError as error:
    fail("write ledger", error)
sys.stdout.flush()
sys.stderr.flush()
os.dup2(stderr_fd, 1)
os.dup2(stderr_fd, 2)
os.write(2, (header + "\\n").encode())
os.execv(CLIENT_BIN, [CLIENT_BIN])
"""


def write_trigger_script(
    path: Path, client_bin: Path = CLIENT_BIN, log_path: Path | None = None
) -> None:
    """Write the TLS-Anvil client trigger script.

    The script is a small generated stdlib-Python program: a single
    ``time.time_ns()`` snapshot yields both the subsecond UTC stamp and the
    integer ``epoch_ns`` used in the per-invocation stderr filename
    (``invocation-<epoch_ns>-<pid>.stderr``, created with ``O_EXCL`` so no
    invocation silently overwrites another), the one-line ledger indexes that
    file, and ``os.execv`` runs the client with no wrapper process — so
    TLS-Anvil observes the client's own PID, exit status, and signal death
    exactly. No shell, ``date``, pipes, or extra per-invocation processes.
    Trigger-internal failures exit ``TRIGGER_FAIL_EXIT`` loudly instead of
    silently dropping the client.
    """
    if log_path is None:
        log_path = path.parent / "anvil_client.invocations.log"
    invocations_dir = log_path.parent / INVOCATIONS_DIR_NAME
    invocations_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(_trigger_script_text(client_bin, log_path, invocations_dir))
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run TLS-Anvil client tests against the ztls client harness."
    )
    parser.add_argument(
        "--port", type=int, default=0, help="local TLS-Anvil server port; 0 picks one"
    )
    parser.add_argument(
        "--timeout", type=int, default=0, help="seconds before stopping TLS-Anvil; 0 disables"
    )
    parser.add_argument("--strength", default="1", help="TLS-Anvil combinatorial strength")
    parser.add_argument("--parallel-tests", default="1", help="TLS-Anvil parallelTests value")
    parser.add_argument(
        "--parallel-handshakes", default="1", help="TLS-Anvil parallelHandshakes value"
    )
    parser.add_argument("--output-folder", type=Path, default=None)
    args, extra = parser.parse_known_args()

    port = args.port or free_port()
    output_folder = args.output_folder or (
        CONF_DIR / "zig-out" / "anvil" / "client" / datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    )
    output_folder.mkdir(parents=True, exist_ok=True)
    logs_dir = output_folder / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    trigger_script = logs_dir / "trigger_client.py"
    write_trigger_script(trigger_script, log_path=logs_dir / "anvil_client.invocations.log")

    cmd = [
        "java",
        "-jar",
        str(ANVIL_JAR),
        "-disableTcpDump",
        "-strength",
        args.strength,
        "-parallelTests",
        args.parallel_tests,
        "-parallelHandshakes",
        args.parallel_handshakes,
        "-outputFolder",
        str(output_folder),
        *extra,
        "client",
        "-port",
        str(port),
        "-triggerScript",
        str(trigger_script),
    ]
    command = " ".join(cmd)
    print(command, flush=True)
    (logs_dir / "TLS-Anvil.command.txt").write_text(command + "\n")
    write_run_metadata(output_folder, command, port, trigger_script)

    env = os.environ.copy()
    env["HOST"] = "127.0.0.1"
    env["PORT"] = str(port)
    env["ZTLS_HOST_NAME"] = "localhost"
    env["ZTLS_INSECURE_NO_CHAIN_ANCHOR"] = "1"
    env["ZTLS_INSECURE_NO_HOST_NAME"] = "1"
    tool_logs_before = snapshot_logs(ANVIL_TOOL_LOG_DIR)
    timeout = args.timeout or None
    stdout_path = logs_dir / "TLS-Anvil.stdout.log"
    try:
        with stdout_path.open("wb") as stdout:
            anvil = subprocess.Popen(
                cmd,
                cwd=CONF_DIR,
                env=env,
                stdout=stdout,
                stderr=subprocess.STDOUT,
            )
            try:
                return anvil.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                terminate(anvil)
                print(
                    f"TLS-Anvil timed out after {args.timeout}s; partial results: {output_folder}",
                    file=sys.stderr,
                )
                return 124
    finally:
        copied = copy_new_logs(ANVIL_TOOL_LOG_DIR, logs_dir, tool_logs_before)
        if copied:
            print(
                "copied TLS-Anvil logs: " + ", ".join(str(p) for p in copied),
                file=sys.stderr,
            )


if __name__ == "__main__":
    raise SystemExit(main())
