/// Simulated TLS 1.3 client handshake demonstration.
///
/// Exercises every handshake primitive we have built, end to end:
///   ClientHello → ServerHello → key schedule → EncryptedExtensions
///   → Certificate → CertificateVerify → server Finished → client Finished
///   → application data
///
/// Uses RFC 8448 §3 known values for the key exchange so the key schedule
/// is deterministic and verifiable. Uses our fixture cert for certificate
/// authentication. The transcript hash is simulated — each step is correct
/// in isolation, not joined by a single live hash.
const std = @import("std");
const crypto = std.crypto;
const print = std.debug.print;

const ztls = @import("ztls");
const hkdf = ztls.hkdf.HkdfSha256;

// Fixture files generated by: just gen-fixtures
const fixture_cert_der = @embedFile("test_fixtures/server.crt.der");
const fixture_cv_sig = @embedFile("test_fixtures/cv.sig");

pub fn main() !void {
    print("=== TLS 1.3 handshake simulation ===\n\n", .{});

    // ── Key Exchange ─────────────────────────────────────────────────────────
    // Use RFC 8448 §3 known keypairs so the transcript is deterministic.

    const client_kp = ztls.x25519.KeyPair{
        .secret_key = .{
            0x49, 0xaf, 0x42, 0xba, 0x7f, 0x79, 0x94, 0x85,
            0x2d, 0x71, 0x3e, 0xf2, 0x78, 0x4b, 0xcb, 0xca,
            0xa7, 0x91, 0x1d, 0xe2, 0x6a, 0xdc, 0x56, 0x42,
            0xcb, 0x63, 0x45, 0x40, 0xe7, 0xea, 0x50, 0x05,
        },
        .public_key = .{
            0x99, 0x38, 0x1d, 0xe5, 0x60, 0xe4, 0xbd, 0x43,
            0xd2, 0x3d, 0x8e, 0x43, 0x5a, 0x7d, 0xba, 0xfe,
            0xb3, 0xc0, 0x6e, 0x51, 0xc1, 0x3c, 0xae, 0x4d,
            0x54, 0x13, 0x69, 0x1e, 0x52, 0x9a, 0xaf, 0x2c,
        },
    };

    const server_public_key = ztls.x25519.PublicKey.init(.{
        0xc9, 0x82, 0x88, 0x76, 0x11, 0x20, 0x95, 0xfe,
        0x66, 0x76, 0x2b, 0xdb, 0xf7, 0xc6, 0x72, 0xe1,
        0x56, 0xd6, 0xcc, 0x25, 0x3b, 0x83, 0x3d, 0xf1,
        0xdd, 0x69, 0xb1, 0xb0, 0x4e, 0x75, 0x1f, 0x0f,
    });

    // ── ClientHello ──────────────────────────────────────────────────────────

    const random: ztls.client_hello.Random = .init(.{
        0xcb, 0x34, 0xec, 0xb1, 0xe7, 0x81, 0x63, 0xba,
        0x1c, 0x38, 0xc6, 0xda, 0xcb, 0x19, 0x6a, 0x6d,
        0xff, 0xa2, 0x1a, 0x8d, 0x99, 0x12, 0xec, 0x18,
        0xa2, 0xef, 0x62, 0x83, 0x02, 0x4d, 0xec, 0xe7,
    });

    var ch_buf: [512]u8 = undefined;
    const client_hello = try ztls.client_hello.encode(
        &ch_buf,
        random,
        .init(client_kp.public_key),
        "server",
    );
    print("[client] ClientHello:          {} bytes\n", .{client_hello.len});

    // ── ServerHello ──────────────────────────────────────────────────────────

    const server_hello_bytes: []const u8 = &.{
        0x02, 0x00, 0x00, 0x56, 0x03, 0x03, 0xa6, 0xaf,
        0x06, 0xa4, 0x12, 0x18, 0x60, 0xdc, 0x5e, 0x6e,
        0x60, 0x24, 0x9c, 0xd3, 0x4c, 0x95, 0x93, 0x0c,
        0x8a, 0xc5, 0xcb, 0x14, 0x34, 0xda, 0xc1, 0x55,
        0x77, 0x2e, 0xd3, 0xe2, 0x69, 0x28, 0x00, 0x13,
        0x01, 0x00, 0x00, 0x2e, 0x00, 0x33, 0x00, 0x24,
        0x00, 0x1d, 0x00, 0x20, 0xc9, 0x82, 0x88, 0x76,
        0x11, 0x20, 0x95, 0xfe, 0x66, 0x76, 0x2b, 0xdb,
        0xf7, 0xc6, 0x72, 0xe1, 0x56, 0xd6, 0xcc, 0x25,
        0x3b, 0x83, 0x3d, 0xf1, 0xdd, 0x69, 0xb1, 0xb0,
        0x4e, 0x75, 0x1f, 0x0f, 0x00, 0x2b, 0x00, 0x02,
        0x03, 0x04,
    };

    const sh = try ztls.server_hello.parse(server_hello_bytes);
    print("[server] ServerHello:          cipher={s}\n", .{@tagName(sh.cipher_suite)});

    // ── Key Schedule ─────────────────────────────────────────────────────────

    const dhe = try ztls.x25519.sharedSecret(client_kp.secret_key, server_public_key);
    const handshake_secret = hkdf.handshakeSecret(hkdf.early_secret, &dhe);

    // Transcript hash: SHA-256(ClientHello || ServerHello) from RFC 8448 §3
    const transcript_hs: hkdf.Prk = .init(.{
        0x86, 0x0c, 0x06, 0xed, 0xc0, 0x78, 0x58, 0xee,
        0x8e, 0x78, 0xf0, 0xe7, 0x42, 0x8c, 0x58, 0xed,
        0xd6, 0xb4, 0x3f, 0x2c, 0xa3, 0xe6, 0xe9, 0x5f,
        0x02, 0xed, 0x06, 0x3c, 0xf0, 0xe1, 0xca, 0xd8,
    });

    const client_hs_secret = hkdf.clientHandshakeTrafficSecret(handshake_secret, &transcript_hs);
    const server_hs_secret = hkdf.serverHandshakeTrafficSecret(handshake_secret, &transcript_hs);

    print("[both]   handshake_secret:     {x}\n", .{handshake_secret.data});

    // ── Handshake RecordLayers ────────────────────────────────────────────────

    var server_tx = hkdf.makeRecordLayer(.aes128_gcm, server_hs_secret);
    var client_rx = hkdf.makeRecordLayer(.aes128_gcm, server_hs_secret);
    var client_tx = hkdf.makeRecordLayer(.aes128_gcm, client_hs_secret);

    print("[both]   handshake keys ready\n\n", .{});

    // ── EncryptedExtensions ───────────────────────────────────────────────────

    const ee_plaintext = [_]u8{ 0x08, 0x00, 0x00, 0x02, 0x00, 0x00 }; // empty extensions
    var ee_wire_buf: [ee_plaintext.len + ztls.RecordLayer.overhead]u8 = undefined;
    const ee_wire = try server_tx.encrypt(.handshake, &ee_plaintext, &ee_wire_buf);

    var ee_dec_buf: [ee_plaintext.len + ztls.RecordLayer.overhead]u8 = undefined;
    @memcpy(ee_dec_buf[0..ee_wire.len], ee_wire);
    const ee_dec = try client_rx.decrypt(&ee_dec_buf);
    try ztls.encrypted_extensions.parse(ee_dec.content);
    print("[server] EncryptedExtensions:  {} wire bytes → parsed\n", .{ee_wire.len});

    // ── Certificate ───────────────────────────────────────────────────────────

    const cert_der = fixture_cert_der;
    const cert_entry_len = cert_der.len + 2;
    const cert_list_len = 3 + cert_entry_len;
    const cert_body_len = 1 + 3 + cert_list_len;
    var cert_plaintext_buf: [1024]u8 = undefined;
    {
        var w: ztls.wire.Writer = .init(&cert_plaintext_buf);
        w.append(u8, 0x0b);
        w.append(u24, @intCast(cert_body_len));
        w.append(u8, 0x00);
        w.append(u24, @intCast(cert_list_len));
        w.append(u24, @intCast(cert_der.len));
        w.appendSlice(cert_der);
        w.append(u16, 0x0000);
        const cert_plaintext = w.written();

        var cert_wire_buf: [1200]u8 = undefined;
        const cert_wire = try server_tx.encrypt(.handshake, cert_plaintext, &cert_wire_buf);

        var cert_dec_buf: [1200]u8 = undefined;
        @memcpy(cert_dec_buf[0..cert_wire.len], cert_wire);
        const cert_dec = try client_rx.decrypt(cert_dec_buf[0..cert_wire.len]);
        print("[server] Certificate:          {} wire bytes\n", .{cert_wire.len});

        // ── CertificateVerify ─────────────────────────────────────────────────

        const cv_sig = fixture_cv_sig;

        var cv_plaintext_buf: [256]u8 = undefined;
        var cw: ztls.wire.Writer = .init(&cv_plaintext_buf);
        cw.append(u8, 0x0f);
        cw.append(u24, @intCast(2 + 2 + cv_sig.len));
        cw.append(u16, 0x0403); // ecdsa_secp256r1_sha256
        cw.append(u16, @intCast(cv_sig.len));
        cw.appendSlice(cv_sig);

        var cv_wire_buf: [512]u8 = undefined;
        const cv_wire = try server_tx.encrypt(.handshake, cw.written(), &cv_wire_buf);

        var cv_dec_buf: [512]u8 = undefined;
        @memcpy(cv_dec_buf[0..cv_wire.len], cv_wire);
        const cv_dec = try client_rx.decrypt(cv_dec_buf[0..cv_wire.len]);

        var transcript_hash: [32]u8 = undefined;
        crypto.hash.sha2.Sha256.hash("test transcript", &transcript_hash, .{});
        try ztls.certificate.authenticate(cert_dec.content, cv_dec.content, &transcript_hash, null, 0);
        print("[server] CertificateVerify:    {} wire bytes → authenticated\n", .{cv_wire.len});
    }

    // ── Server Finished ───────────────────────────────────────────────────────

    const server_finished_key = hkdf.finishedKey(server_hs_secret);
    const server_transcript: [32]u8 = .{
        0x96, 0x08, 0x10, 0x2a, 0x0f, 0x1c, 0xcc, 0x6d,
        0xb6, 0x25, 0x0b, 0x7b, 0x7e, 0x41, 0x7b, 0x1a,
        0x00, 0x0e, 0xaa, 0xda, 0x3d, 0xaa, 0xe4, 0x77,
        0x7a, 0x76, 0x86, 0xc9, 0xff, 0x83, 0xdf, 0x13,
    };

    var sf_plaintext_buf: [64]u8 = undefined;
    const sf_plaintext = try ztls.finished.encode(&sf_plaintext_buf, &server_finished_key.data, &server_transcript);
    var sf_wire_buf: [64 + ztls.RecordLayer.overhead]u8 = undefined;
    const sf_wire = try server_tx.encrypt(.handshake, sf_plaintext, &sf_wire_buf);

    var sf_dec_buf: [64 + ztls.RecordLayer.overhead]u8 = undefined;
    @memcpy(sf_dec_buf[0..sf_wire.len], sf_wire);
    const sf_dec = try client_rx.decrypt(&sf_dec_buf);
    try ztls.finished.verify(sf_dec.content, &server_finished_key.data, &server_transcript);
    print("[server] Finished:             {} wire bytes → MAC verified\n", .{sf_wire.len});

    // ── Client Finished ───────────────────────────────────────────────────────

    const client_finished_key = hkdf.finishedKey(client_hs_secret);
    var cf_plaintext_buf: [64]u8 = undefined;
    const cf_plaintext = try ztls.finished.encode(&cf_plaintext_buf, &client_finished_key.data, &server_transcript);
    var cf_wire_buf: [64 + ztls.RecordLayer.overhead]u8 = undefined;
    const cf_wire = try client_tx.encrypt(.handshake, cf_plaintext, &cf_wire_buf);
    print("[client] Finished:             {} wire bytes → sent\n\n", .{cf_wire.len});

    // ── Application Traffic Keys ──────────────────────────────────────────────

    const master_secret = hkdf.masterSecret(handshake_secret);
    const app_transcript: hkdf.Prk = .init(.{
        0x96, 0x08, 0x10, 0x2a, 0x0f, 0x1c, 0xcc, 0x6d,
        0xb6, 0x25, 0x0b, 0x7b, 0x7e, 0x41, 0x7b, 0x1a,
        0x00, 0x0e, 0xaa, 0xda, 0x3d, 0xaa, 0xe4, 0x77,
        0x7a, 0x76, 0x86, 0xc9, 0xff, 0x83, 0xdf, 0x13,
    });
    const server_ap_secret = hkdf.clientApplicationTrafficSecret(master_secret, &app_transcript);

    var app_server_tx = hkdf.makeRecordLayer(.aes128_gcm, server_ap_secret);
    var app_client_rx = hkdf.makeRecordLayer(.aes128_gcm, server_ap_secret);

    print("=== application data ===\n\n", .{});

    const message = "Hello from ztls!";
    var app_buf: [message.len + ztls.RecordLayer.overhead]u8 = undefined;
    const app_wire = try app_server_tx.encrypt(.application_data, message, &app_buf);
    print("[server] encrypted:  {} bytes → {} wire bytes\n", .{ message.len, app_wire.len });

    var app_dec_buf: [message.len + ztls.RecordLayer.overhead]u8 = undefined;
    @memcpy(app_dec_buf[0..app_wire.len], app_wire);
    const app_dec = try app_client_rx.decrypt(&app_dec_buf);
    print("[client] decrypted:  {s}\n", .{app_dec.content});
}
